### ISSUE TITLE
How can I get the nuscenes_prediction_infos_val.json?

### ISSUE THREAD

**Issue by sean-wade** [Tsinghua-MARS-Lab/ViP3D#11]
I want to evaluate on nuscenes-mini dataset. But the nuscenes_prediction_infos_val.json in the project is the whole dataset's?

Is there any code that generate nuscenes_prediction_infos_val.json?

**Comment by GentleSmile** [comment]
First rename your `data/nuscenes-mini` to `data/nuscenes`, then generate nuscenes prediction infos at test time:
```
PYTHONPATH=. python tools/test.py plugin/vip3d/configs/vip3d_resnet50_3frame.py work_dirs/vip3d_resnet50_3frame.1/epoch_24.pth --eval bbox --cfg-options model.generate_nuscenes_prediction_infos_val=True data.workers_per_gpu=0
```
Then it will be saved at `data/nuscenes`.

**Comment by sean-wade** [comment]
OK, thanks for the reply!
