### ISSUE TITLE
How to generate the nuscenes_prediction_infos_val.json for the mini data？

### ISSUE THREAD

**Issue by OopsYHQ** [Tsinghua-MARS-Lab/ViP3D#16]
I tried running 
`PYTHONPATH=. python tools/test.py plugin/vip3d/configs/vip3d_resnet50_3frame.py work_dirs/vip3d_resnet50_3frame.1/epoch_24.pth --eval bbox --cfg- options model.generate_nuscenes_prediction_infos_val=True data.workers_per_gpu=0`
 but no success. Is it possible that the code in question hasn't been updated yet?
![1](https://github.com/Tsinghua-MARS-Lab/ViP3D/assets/83757277/f89cfd3d-3220-4c16-8753-38d8bce1bc0e)

**Comment by GentleSmile** [comment]
Sorry, what about using the following command:
```
PYTHONPATH=. python tools/test.py plugin/vip3d/configs/vip3d_resnet50_3frame.py work_dirs/vip3d_resnet50_3frame.1/epoch_24.pth --eval bbox --cfg-options data.test.generate_nuscenes_prediction_infos_val=True data.workers_per_gpu=0
```

**Comment by OopsYHQ** [comment]
thank you!!I find it!
