### ISSUE TITLE
How to visualize?

### ISSUE THREAD

**Issue by miraclesheephaha** [Tsinghua-MARS-Lab/ViP3D#18]
If I want to achieve visualization, do I need to get results_nusc.json first, and then use vip3d.py to read the information of results_nusc.json?
looking forward to your reply, thank you.

**Comment by GentleSmile** [comment]
We have not released the visualization code because the tool is complicated to deploy, see #12

**Comment by miraclesheephaha** [comment]
So if I write visual programming code, the data that need to be input include result_nusc.json and the label file in the nuscenes data set, right?
Thank you for your answer.

**Comment by GentleSmile** [comment]
The result_nusc.json file is almost the same as the output of MUTR3D, with the only difference being that ViP3D has two additional fields: `pred_outputs` and `pred_probs` [here](https://github.com/Tsinghua-MARS-Lab/ViP3D/blob/c4a60b01a4b5d68289c1958d2e6935ed73d76964/plugin/vip3d/dataset.py#L1032).

**Comment by miraclesheephaha** [comment]
Where is the calculation method of pred_outputs written in the program code? Because I don't know its calculation method, it is difficult to draw the results output by pred_outputs in a lidar or camera diagram.
looking forward to your reply,thank you.

**Comment by GentleSmile** [comment]
`pred_outputs` is directly output by the predictor (see [line](https://github.com/Tsinghua-MARS-Lab/ViP3D/blob/c4a60b01a4b5d68289c1958d2e6935ed73d76964/plugin/vip3d/models/vip3d.py#L978)), it is in the ego vehicle coordinate system (not lidar system).
