### ISSUE TITLE
Heatmap-based and Goal-based ViP3D

### ISSUE THREAD

**Issue by yihongXU** [Tsinghua-MARS-Lab/ViP3D#3]
Dear authors,

Thanks for sharing the code of ViP3D! It is rare but very important to the motion forecasting community.
Would it be possible to have the code for heatmap-based and goal-based ViP3D?

Best,

**Comment by GentleSmile** [comment]
We conduct experiments of goal-based and heatmap-based methods just for ablation study. The implementation is not fine-tuned, so they do not perform better than regression-based in some metrics. You can refer to HOME/DenseTNT papers or open source code.

**Comment by yihongXU** [comment]
Hi,

Thank you for your replay. I'll check DenseTNT.
